### PR TITLE
With bias T and TCXO correction

### PR DESCRIPTION
**Pull request by g8sqh**
I am using an FCDPP for meteor scatter off the GRAVES radar, so I needed bias tee for the pre-amp.
My FCDPP is well off frequency (8.4ppm) , so I also added frequency correction. (Since there's none in the hardware, I apply the correction as the FCDPP is being loaded)

If these patches are useful, please have them

### CODE REVIEW

**Comment by guruofquality** [comment]
Seems good to me. One comment is that treating the bias t like a gain element might be strange to some. I don't have the hardware, I cant say if that makes sense. SDRPlay for example, exposes it through writeSetting: https://github.com/pothosware/SoapySDRPlay/blob/master/Settings.cpp#L1055 Thoughts?

**Comment by zuckschwerdt** [comment]
Bias-t will affect the gain, but it is not a gain element itself. The gains on this device are simple toggles but the api really wants a dB value there which also doesn't fit with bias-t.

Another thing to watch out for: a common flow in applications is to set ppm early, then set the frequency as needed. I.e. I wouldn't expect the ppm setting to tune away.
Perhaps you could check for freq=0 and then not set a frequency in the ppm setter, or use fcdpp_get_freq_hz. I don't know if the tuning is "sticky" for this device though -- it is for some other devices (i.e. just opening devices will retain the last setting).

**Comment by g8sqh** [comment]
There's no frequency correction in the hardware/firmware, so it doesn't persist. Fixed code to not set frequency unless tuned.

The settings API might be best for bias T, but not supported in gqrx. I've moved the bias tee to be a type of antenna - which is a toggle effectively

**Comment by J-Luc16** [comment]
> 
> 
> I am using an FCDPP for meteor scatter off the GRAVES radar, so I needed bias tee for the pre-amp.
> My FCDPP is well off frequency (8.4ppm) , so I also added frequency correction. (Since there's none in the hardware, I apply the correction as the FCDPP is being loaded)
> 
> If these patches are useful, please have them

Hi,

I have the same application from here but I wonder where you put all the parameters in the config file of openwebrx for example.

Best regards
J-Luc F1JEK

**Comment by guruofquality** [comment]
Sorry, this was forgotten about. I didnt realize the pull was updated.

**Comment by g8sqh** [comment]
Thanks for the commit - I'll try it out. For info - it works on a BeagleBone Black - one of the few small ARMs that has properly done USB (and hence will run at 192k)

F1JEK - openwebrx is new to me. It seems to use rx_sdr to get the I&Q streams. [https://github.com/ha7ilm/openwebrx/issues/114](https://github.com/ha7ilm/openwebrx/issues/114) gives an example of what to put in config_webrx.py. **Think this may be totally out of date - sorry. config_webrx looks totally different**
Looking at  [https://github.com/rxseger/rx_tools/blob/master/src/rtl_sdr.c](https://github.com/rxseger/rx_tools/blob/master/src/rtl_sdr.c)   the options needed are -p to set the ppm correction, and -a to enable the bias tee. Specifically Bias_T_Off and Bias_T_On are the names for the antenna after -a

Note that the -p option to rx_sdr takes an integer. My code accepts a float, and gqrx allows 1 decimal place on ppm correction. 

Looking at [https://github.com/jketterl/openwebrx/blob/develop/owrx/source/connector.py](url) there's a problem - ConnectorSource uses -P for ppm correction (-p for port number), and rx_sdr uses -p. So 'antenna' in config_webrx.py should go to -a in the command, but getting ppm will be harder

**Pull request merged**
