### PR TITLE
Use direct buffer (mmap) access to reduce CPU load slightly

### PR DESCRIPTION
**Pull request by phlash**
Added compile time option to use ALSA direct buffer (mmap) access to reduce memory copies and save a little CPU time. Useful on limited resource devices (such as Pi Zero or clones).

Testing with local FM stations shows this operates similarly to memory copy implementation, with ~25% load reduction.

### CODE REVIEW

**Comment by guruofquality** [comment]
Thats pretty cool. If its safe to always compile mmap API in, I would just ditch the ifdefs and make it a runtime option based on a device arg. If not, I would give the CMakeLists.txt an option so the mmap compiling could be disabled if need be: https://cmake.org/cmake/help/latest/command/option.html

**Comment by phlash** [comment]
As I understand it, ALSA always uses a memory mapped ring buffer between kernel and userland, so this simply removes one copy between that and a temporary read buffer in the app, before conversion and/or copying out to the API caller, so I think it's safe to assume we can always do this on Linux. We will want to revisit this if anyone ports SoapyFCDPP to other OS of course, probably taking a lead from SoapyAudio.

[edited to add] This of course opens the door for the SoapySDR direct buffer API too, I'll look at that next :smile:

**Comment by phlash** [comment]
Direct buffer API now in my tree https://github.com/phlash/SoapyFCDPP/tree/direct-api, happy to bring this in and merged once #12 in in :smile:

**Comment by phlash** [comment]
Completed direct buffer API, along with a test program (as SoapySDRUtil doesn't use it). Let me know if you think this should be elsewhere :smile: I'm happy to merge this if you are.

**Pull request merged**
